/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cloud_22.glb -o src/components/Cloud_22.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud_22({opacity,...props}) {
  const { nodes, materials } = useGLTF('/cloud_22.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.secondballcloud001.geometry} >
        <meshStandardMaterial {...materials['nodes.secondballcloud001.material']} transparent opacity={opacity}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/cloud_22.glb')
