/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/clouds.glb -o src/components/Clouds.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud({opacity,...props}) {
  const { nodes, materials } = useGLTF('/clouds.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry}>
        <meshStandardMaterial {...materials['lambert2SG.001']} transparent opacity={opacity} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/clouds.glb')
