/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cloud_11.glb -o src/components/Cloud_11.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud_11({opacity,...props}) {
  const { nodes, materials } = useGLTF('/cloud_11.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cloudball001.geometry} >
        <meshStandardMaterial {...materials['nodes.cloudball001.material']} transparent opacity={opacity} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/cloud_11.glb')
