/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/planeur.glb -o src/components/MyPlaneur.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planeur(props) {
  const { nodes, materials } = useGLTF('/planeur.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} />
    </group>
  )
}

useGLTF.preload('/planeur.glb')
