/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/heart.glb -o src/components/Heart.jsx -r public -k 
*/

import { useEffect , useRef} from 'react'
import * as THREE from 'three'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

function Heart(props) {
  const { nodes, materials } = useGLTF('/heart.glb')
  const group = useRef();

  useEffect(()=>{

    const groupWorldPosition = new THREE.Vector3();
    group.current.getWorldPosition(groupWorldPosition); 

    group.current.children.forEach((mesh)=>{
      mesh.orignalPosition = mesh.position.clone();
      const meshWorldPosition = new THREE.Vector3();
      mesh.getWorldPosition(meshWorldPosition);

      mesh.directionVector  = meshWorldPosition.clone().sub(groupWorldPosition).normalize();
      mesh.targetPosition = mesh.orignalPosition.clone().add(mesh.directionVector.clone().multiplyScalar(0.5));
    })
  })

  const scrollData = useScroll();
  useFrame(() => {
    group.current.children.forEach((mesh)=>{
      if(scrollData.offset < 0.0001){
        if(mesh.name === "origin"){
          mesh.visible = true;
        } else { 
          mesh.visible = false
        }
      }
      else {
        if(mesh.name === "origin"){
          mesh.visible= false;
        }
        else {
          mesh.visible = true;
        }
      }
      mesh.position.x = THREE.MathUtils.lerp(mesh.orignalPosition.x,mesh.targetPosition.x,scrollData.offset)
      mesh.position.y = THREE.MathUtils.lerp(mesh.orignalPosition.y,mesh.targetPosition.y,scrollData.offset)
      mesh.position.z = THREE.MathUtils.lerp(mesh.orignalPosition.z,mesh.targetPosition.z,scrollData.offset)
    })
  })

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh name="Heart_Full_cell" geometry={nodes.Heart_Full_cell.geometry} material={materials.Red} position={[0.225, -0.262, 0.123]} />
      <mesh name="Heart_Full_cell001" geometry={nodes.Heart_Full_cell001.geometry} material={materials.Red} position={[0.224, 0.206, -0.04]} />
      <mesh name="Heart_Full_cell002" geometry={nodes.Heart_Full_cell002.geometry} material={materials.Red} position={[-0.375, 0.12, -0.017]} />
      <mesh name="Heart_Full_cell003" geometry={nodes.Heart_Full_cell003.geometry} material={materials.Red} position={[-0.072, -0.379, 0.077]} />
      <mesh name="Heart_Full_cell004" geometry={nodes.Heart_Full_cell004.geometry} material={materials.Red} position={[-0.341, -0.119, 0.097]} />
      <mesh name="Heart_Full_cell005" geometry={nodes.Heart_Full_cell005.geometry} material={materials.Red} position={[0.191, -0.134, 0.183]} />
      <mesh name="Heart_Full_cell006" geometry={nodes.Heart_Full_cell006.geometry} material={materials.Red} position={[0.309, -0.12, -0.153]} />
      <mesh name="Heart_Full_cell007" geometry={nodes.Heart_Full_cell007.geometry} material={materials.Red} position={[0.074, -0.16, 0.179]} />
      <mesh name="Heart_Full_cell008" geometry={nodes.Heart_Full_cell008.geometry} material={materials.Red} position={[0.379, 0.116, -0.008]} />
      <mesh name="Heart_Full_cell009" geometry={nodes.Heart_Full_cell009.geometry} material={materials.Red} position={[0.337, -0.02, -0.155]} />
      <mesh name="Heart_Full_cell010" geometry={nodes.Heart_Full_cell010.geometry} material={materials.Red} position={[0.212, 0.005, 0.206]} />
      <mesh name="Heart_Full_cell011" geometry={nodes.Heart_Full_cell011.geometry} material={materials.Red} position={[-0.222, 0.211, 0.011]} />
      <mesh name="Heart_Full_cell012" geometry={nodes.Heart_Full_cell012.geometry} material={materials.Red} position={[-0.159, 0.1, -0.187]} />
      <mesh name="Heart_Full_cell013" geometry={nodes.Heart_Full_cell013.geometry} material={materials.Red} position={[-0.279, 0.11, 0.159]} />
      <mesh name="Heart_Full_cell014" geometry={nodes.Heart_Full_cell014.geometry} material={materials.Red} position={[0.079, -0.369, 0.085]} />
      <mesh name="Heart_Full_cell015" geometry={nodes.Heart_Full_cell015.geometry} material={materials.Red} position={[-0.193, -0.02, 0.198]} />
      <mesh name="Heart_Full_cell016" geometry={nodes.Heart_Full_cell016.geometry} material={materials.Red} position={[0.306, -0.175, -0.012]} />
      <mesh name="Heart_Full_cell017" geometry={nodes.Heart_Full_cell017.geometry} material={materials.Red} position={[-0.212, -0.018, -0.217]} />
      <mesh name="Heart_Full_cell018" geometry={nodes.Heart_Full_cell018.geometry} material={materials.Red} position={[0.153, -0.279, 0.015]} />
      <mesh name="Heart_Full_cell019" geometry={nodes.Heart_Full_cell019.geometry} material={materials.Red} position={[-0.373, -0.11, -0.05]} />
      <mesh name="Heart_Full_cell020" geometry={nodes.Heart_Full_cell020.geometry} material={materials.Red} position={[0.375, 0, 0.071]} />
      <mesh name="Heart_Full_cell021" geometry={nodes.Heart_Full_cell021.geometry} material={materials.Red} position={[-0.307, 0.171, 0.071]} />
      <mesh name="Heart_Full_cell022" geometry={nodes.Heart_Full_cell022.geometry} material={materials.Red} position={[0.152, -0.13, -0.142]} />
      <mesh name="Heart_Full_cell023" geometry={nodes.Heart_Full_cell023.geometry} material={materials.Red} position={[-0.188, 0.184, -0.111]} />
      <mesh name="Heart_Full_cell024" geometry={nodes.Heart_Full_cell024.geometry} material={materials.Red} position={[0.349, -0.104, 0.127]} />
      <mesh name="Heart_Full_cell025" geometry={nodes.Heart_Full_cell025.geometry} material={materials.Red} position={[-0.305, -0.183, -0.013]} />
      <mesh name="Heart_Full_cell026" geometry={nodes.Heart_Full_cell026.geometry} material={materials.Red} position={[-0.391, 0.006, 0.058]} />
      <mesh name="Heart_Full_cell027" geometry={nodes.Heart_Full_cell027.geometry} material={materials.Red} position={[0.248, -0.244, -0.111]} />
      <mesh name="Heart_Full_cell028" geometry={nodes.Heart_Full_cell028.geometry} material={materials.Red} position={[-0.003, 0.15, -0.124]} />
      <mesh name="Heart_Full_cell029" geometry={nodes.Heart_Full_cell029.geometry} material={materials.Red} position={[-0.002, -0.277, -0.071]} />
      <mesh name="Heart_Full_cell030" geometry={nodes.Heart_Full_cell030.geometry} material={materials.Red} position={[-0.015, -0.034, 0.151]} />
      <mesh name="Heart_Full_cell031" geometry={nodes.Heart_Full_cell031.geometry} material={materials.Red} position={[0.349, 0.113, -0.101]} />
      <mesh name="Heart_Full_cell032" geometry={nodes.Heart_Full_cell032.geometry} material={materials.Red} position={[-0.141, 0.129, 0.164]} />
      <mesh name="Heart_Full_cell033" geometry={nodes.Heart_Full_cell033.geometry} material={materials.Red} position={[-0.169, -0.133, -0.145]} />
      <mesh name="Heart_Full_cell034" geometry={nodes.Heart_Full_cell034.geometry} material={materials.Red} position={[-0.392, -0.001, -0.059]} />
      <mesh name="Heart_Full_cell035" geometry={nodes.Heart_Full_cell035.geometry} material={materials.Red} position={[0.342, 0.086, 0.15]} />
      <mesh name="Heart_Full_cell036" geometry={nodes.Heart_Full_cell036.geometry} material={materials.Red} position={[0.398, -0.031, -0.065]} />
      <mesh name="Heart_Full_cell037" geometry={nodes.Heart_Full_cell037.geometry} material={materials.Red} position={[-0.093, 0.202, 0.011]} />
      <mesh name="Heart_Full_cell038" geometry={nodes.Heart_Full_cell038.geometry} material={materials.Red} position={[0.001, 0.037, 0.011]} />
      <mesh name="Heart_Full_cell039" geometry={nodes.Heart_Full_cell039.geometry} material={materials.Red} position={[0.088, -0.299, 0.186]} />
      <mesh name="Heart_Full_cell040" geometry={nodes.Heart_Full_cell040.geometry} material={materials.Red} position={[0.168, 0.17, 0.131]} />
      <mesh name="Heart_Full_cell041" geometry={nodes.Heart_Full_cell041.geometry} material={materials.Red} position={[-0.099, -0.308, 0.193]} />
      <mesh name="Heart_Full_cell042" geometry={nodes.Heart_Full_cell042.geometry} material={materials.Red} position={[0.065, -0.41, -0.07]} />
      <mesh name="Heart_Full_cell043" geometry={nodes.Heart_Full_cell043.geometry} material={materials.Red} position={[-0.217, -0.243, 0.116]} />
      <mesh name="Heart_Full_cell044" geometry={nodes.Heart_Full_cell044.geometry} material={materials.Red} position={[-0.097, -0.163, 0.176]} />
      <mesh name="Heart_Full_cell045" geometry={nodes.Heart_Full_cell045.geometry} material={materials.Red} position={[0.102, 0.205, -0.029]} />
      <mesh name="Heart_Full_cell046" geometry={nodes.Heart_Full_cell046.geometry} material={materials.Red} position={[-0.325, -0.016, 0.151]} />
      <mesh name="Heart_Full_cell047" geometry={nodes.Heart_Full_cell047.geometry} material={materials.Red} position={[-0.164, -0.273, 0.018]} />
      <mesh name="Heart_Full_cell048" geometry={nodes.Heart_Full_cell048.geometry} material={materials.Red} position={[0, 0, -0.199]} />
      <mesh name="Heart_Full_cell049" geometry={nodes.Heart_Full_cell049.geometry} material={materials.Red} position={[0.109, -0.268, -0.122]} />
      <mesh name="Heart_Full_cell050" geometry={nodes.Heart_Full_cell050.geometry} material={materials.Red} position={[-0.33, -0.061, -0.153]} />
      <mesh name="Heart_Full_cell051" geometry={nodes.Heart_Full_cell051.geometry} material={materials.Red} position={[-0.328, 0.117, -0.111]} />
      <mesh name="Heart_Full_cell052" geometry={nodes.Heart_Full_cell052.geometry} material={materials.Red} position={[0.303, 0.176, 0.087]} />
      <mesh name="Heart_Full_cell053" geometry={nodes.Heart_Full_cell053.geometry} material={materials.Red} position={[0.266, 0.116, -0.157]} />
      <mesh name="Heart_Full_cell054" geometry={nodes.Heart_Full_cell054.geometry} material={materials.Red} position={[0.201, -0.007, -0.205]} />
      <mesh name="Heart_Full_cell055" geometry={nodes.Heart_Full_cell055.geometry} material={materials.Red} position={[-0.072, -0.411, -0.066]} />
      <mesh name="Heart_Full_cell056" geometry={nodes.Heart_Full_cell056.geometry} material={materials.Red} position={[0.145, 0.133, -0.162]} />
      <mesh name="Heart_Full_cell057" geometry={nodes.Heart_Full_cell057.geometry} material={materials.Red} position={[-0.231, -0.132, 0.175]} />
      <mesh name="Heart_Full_cell058" geometry={nodes.Heart_Full_cell058.geometry} material={materials.Red} position={[-0.114, -0.267, -0.123]} />
      <mesh name="Heart_Full_cell059" geometry={nodes.Heart_Full_cell059.geometry} material={materials.Red} position={[0.001, -0.2, 0.175]} />
      <mesh name="Heart_Full_cell060" geometry={nodes.Heart_Full_cell060.geometry} material={materials.Red} position={[0.001, -0.162, -0.126]} />
      <mesh name="Heart_Full_cell061" geometry={nodes.Heart_Full_cell061.geometry} material={materials.Red} position={[-0.269, -0.219, -0.133]} />
      <mesh name="origin" geometry={nodes.Origin.geometry} material={materials.Red} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/heart.glb')

export default Heart;
